apiVersion: apps/v1
kind: Deployment
metadata:
  name: servreservas-deployment
spec:
  selector:
    matchLabels:
      app: servreservas-pod
  template:
    metadata:
      labels:
        app: servreservas-pod
    spec:
      containers:
      - name: servreservas-container
        image: crredbici.azurecr.io/serreser:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
